version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: techwear_db
      POSTGRES_USER: techwear_user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://techwear_user:techwear_pass@postgres:5432/techwear_db
    volumes:
      - .:/app

volumes:
  postgres_data: