version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: techwear_db
      POSTGRES_USER: techwear_user
      POSTGRES_PASSWORD: techwear_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: techwear_db
      DB_USER: techwear_user
      DB_PASSWORD: techwear_password
    volumes:
      - .:/app

volumes:
  postgres_data: